### ISSUE TITLE
Wrong settings for pt-BR on system.json file

### ISSUE THREAD

**Issue by johcker** [DrOgres/tftloop#7] opened 2021-02-14 01:06 UTC
The configuration for the Brazilian Portuguese language is wrong at system.json file, so the translation doesn't work on foundryvtt (it doesn't load).
The correct configuration is something like that:

`{
        "lang": "pt-BR",
        "name": "Portuguese (Brazilian)",
        "path": "lang/pt-BR.json"
    } `

I've tested this change locally (image attached).

![tales_pt-BR](https://user-images.githubusercontent.com/2867140/107865642-6b7cb380-6e47-11eb-82e4-f24a6962dbba.png)

PS.: Congratulations for the sheet and for its translation.

**Comment by DrOgres** [comment] 2021-02-14 01:36
Hmm.. well I did notice that the system settings had two entries for Português (Brasil) in the language list and still does when i change the language to pt-br, one will apply the language pack the other will not. I am not certain what the issue is.  for now be certain you are using the first one in the list.  

I will continue to investigate and find out what needs fixing 

Thanks for using the system and I hope your games go amazingly well!
![pt-br](https://user-images.githubusercontent.com/74268782/107866120-d1127500-6e32-11eb-91a4-8de3bdac395c.png)

**Comment by johcker** [comment] 2021-02-14 02:14
Again: the correct is pt-BR (with caps into BR letters), just take a look in the another systems.
And just pt-PT is for original portuguese (from Portugal). The system.json mix them up!

examples attached:

![call_of_cthulhu_7](https://user-images.githubusercontent.com/2867140/107866561-f57d4a00-6e50-11eb-9604-c79f266f707f.png)

![shadow_of_the_demon_lord](https://user-images.githubusercontent.com/2867140/107866565-fdd58500-6e50-11eb-82c2-c93fb5295351.png)

This is the pattern: https://support.mozilla.org/pt-BR/kb/abreviacao-de-localizacao

**Comment by DrOgres** [comment] 2021-02-14 02:23
Ahh!  ok got it thanks!

**Comment by johcker** [comment] 2021-02-14 02:24
After the fix, it shows only one option here:

![only_one](https://user-images.githubusercontent.com/2867140/107866729-7be65b80-6e52-11eb-9627-253767804da4.png)

**Comment by DrOgres** [comment] 2021-02-14 02:27
this is fixed in 0.8.96

thanks again!  I will also look at formatting so that the longer strings (like luck points) don't break the layout but that will be a few days.

**Closed by DrOgres** 2021-02-14 02:27 UTC
